### ISSUE TITLE
Failed to sync

### ISSUE THREAD

**Issue by pShatha** [catalyst/moodle-tool_cohortdatabase#21] opened 2023-05-31 16:45 UTC
when i run the cron always i got this "Failed to sync because the external db returned 0 records" although the external db has 4 rows

**Comment by danmarsden** [comment] 2023-06-07 08:26
probably a setting/table/column you might have wrong in there - we'd need to see your db and table to verify this and that's not the sort of support we provide for free sorry! - as I can't reproduce this I'll need to close it as "cannot reproduce" but feel free to reach out privately if you would like commercial support to help you use the plugin.

**Closed as completed by danmarsden** 2023-06-07 08:26 UTC
